# Generated by Django 6.0 on 2026-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('codes', 'Codes'), ('district_rates', 'District Rates'), ('rules', 'Rules and Regulations'), ('notes', 'Notes'), ('blogs', 'Blogs')], max_length=50)),
                ('region', models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('us', 'US'), ('europe', 'Europe'), ('other', 'Other')], max_length=50)),
                ('sub_items_count', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
