# Generated by Django 6.0 on 2026-05-05 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdfs/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
