# Generated by Django 6.0 on 2026-05-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resource_pdf_file_alter_resource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('STRUCTURAL', 'Structural'), ('MATERIAL', 'Material'), ('COST', 'Cost Estimation'), ('GENERAL', 'General')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('LENGTH', 'Length'), ('AREA', 'Area'), ('VOLUME', 'Volume')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('default_value', models.FloatField(default=0)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='accounts.calculator')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('factor', models.FloatField()),
                ('converter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.converter')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='accounts.resource')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('LINK', 'Link'), ('NOTE', 'Note')], max_length=20)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.subitem')),
            ],
        ),
    ]
