# Generated by Django 6.0 on 2026-05-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_slug_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subitem',
            index=models.Index(fields=['slug'], name='accounts_su_slug_baeb87_idx'),
        ),
    ]
