# Generated by Django 6.0 on 2026-05-10 13:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='content_mode',
            field=models.CharField(choices=[('direct', 'Direct content page'), ('sections', 'Open sections first')], default='sections', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/sections/'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.subitem'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='accounts.resource')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='accounts.subitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.chapter'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('note', 'Note'), ('formula', 'Formula'), ('pdf', 'PDF'), ('embed', 'Embedded material'), ('practice', 'Practice question'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/content/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='accounts.chapter')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='accounts.resource')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='accounts.subitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['slug'], name='accounts_ch_slug_3f8b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['resource', 'slug'], name='accounts_ch_resourc_9e485f_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['section', 'slug'], name='accounts_ch_section_4f60c0_idx'),
        ),
    ]
