# Generated by Django 6.0 on 2026-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_file_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('note', 'Note'), ('summary', 'Summary'), ('table', 'Table'), ('formula', 'Formula'), ('pdf', 'PDF'), ('embed', 'Embedded material'), ('practice', 'Practice question'), ('video', 'Video')], max_length=20),
        ),
    ]
