# Generated by Django 6.0 on 2026-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubItem',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='subitem',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subitem',
            new_name='section',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='accounts_se_slug_9c8fb8_idx',
            old_name='accounts_su_slug_baeb87_idx',
        ),
    ]
